name: argprism
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py313h321d83c_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.8.6=hd08a7f5_4
  - aws-c-cal=0.8.7=h043a21b_0
  - aws-c-common=0.12.0=hb9d3cd8_0
  - aws-c-compression=0.3.1=h3870646_2
  - aws-c-event-stream=0.5.4=h04a3f94_2
  - aws-c-http=0.9.4=hb9b18c6_4
  - aws-c-io=0.17.0=h3dad3f2_6
  - aws-c-mqtt=0.12.2=h108da3e_2
  - aws-c-s3=0.7.13=h822ba82_2
  - aws-c-sdkutils=0.2.3=h3870646_2
  - aws-checksums=0.2.3=h3870646_2
  - aws-crt-cpp=0.31.0=h55f77e1_4
  - aws-sdk-cpp=1.11.510=h37a5c72_3
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - biopython=1.85=py313h07c4f96_2
  - boto3=1.37.7=pyhd8ed1ab_0
  - botocore=1.37.38=pyge310_1234567_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py313h7033f15_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py313hf46b229_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py313h7037e92_3
  - cpython=3.13.10=py313hd8ed1ab_100
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.2.1=pyhd8ed1ab_0
  - dbus=1.16.2=h24cb091_1
  - diamond=2.1.16=h13889ed_0
  - dill=0.4.0=pyhcf101f3_1
  - double-conversion=3.3.1=h5888daf_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - frozenlist=1.7.0=py313h6b9daa2_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - git=2.52.0=pl5321h28be001_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py313h86d8783_2
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.13.0=nompi_py313hfaf8fd4_101
  - harfbuzz=12.2.0=h15599e2_0
  - hdf5=1.14.6=nompi_h1b119a7_104
  - hf-xet=1.2.1=py310hb823017_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libaec=1.1.4=h3f801dc_0
  - libarrow=19.0.1=hc7b3859_3_cpu
  - libarrow-acero=19.0.1=hcb10f89_3_cpu
  - libarrow-dataset=19.0.1=hcb10f89_3_cpu
  - libarrow-substrait=19.0.1=h08228c5_3_cpu
  - libblas=3.11.0=4_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.11.0=4_h0358290_openblas
  - libclang-cpp21.1=21.1.0=default_h99862b1_1
  - libclang13=21.1.0=default_h746c552_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.2=h32235b2_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_14
  - libgoogle-cloud=2.36.0=h2b5623c_0
  - libgoogle-cloud-storage=2.36.0=h0121fbd_0
  - libgrpc=1.67.1=h25350d4_2
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=4_h47877c9_openblas
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.18.0=hfcad708_1
  - libopentelemetry-cpp-headers=1.18.0=ha770c72_1
  - libparquet=19.0.1=h081d1f1_3_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.51=h421ea60_0
  - libpq=17.7=h5c52fec_1
  - libprotobuf=5.28.3=h6128344_1
  - libre2-11=2024.07.02=hbbce691_2
  - libsentencepiece=0.2.0=h8e10757_10
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_14
  - libstdcxx-ng=15.2.0=hdf11a46_14
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.1=h9d88235_1
  - libtorch=2.6.0=cpu_generic_haed06de_0
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.41.2=h5347b49_1
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.9=h04c0eec_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib=3.10.1=py313h78bf25f_0
  - matplotlib-base=3.10.1=py313h129903b_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py313h8060acc_0
  - multiprocess=0.70.18=py313h54dd161_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6=pyhcf101f3_0
  - nlohmann_json=3.12.0=h54a6638_1
  - nomkl=1.0=h5ca1d4c_0
  - numpy=2.2.3=py313h17eae1a_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - optree=0.18.0=py313h7037e92_0
  - orc=2.1.1=h2271f48_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py313ha87cce1_3
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - perl=5.32.1=7_hd590300_perl5
  - pillow=11.2.1=py313h8db990d_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - prometheus-cpp=1.3.0=ha5d0236_0
  - propcache=0.3.1=py313h8060acc_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=19.0.1=py313h78bf25f_0
  - pyarrow-core=19.0.1=py313he5f92c8_0_cpu
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.2=py313ha3f37dd_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.10=hc97d973_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.10=h4df99d1_100
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py313heab5758_1
  - python_abi=3.13=8_cp313
  - pytorch=2.6.0=cpu_generic_py313_h4767f55_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h3dea7bd_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.2=h5bd77bc_1
  - re2=2024.07.02=h9925aae_2
  - readline=8.2=h8c095d6_2
  - regex=2024.11.6=py313h536fd9c_0
  - requests=2.32.3=pyhd8ed1ab_1
  - responses=0.18.0=pyhd8ed1ab_0
  - s2n=1.5.14=h6c98b2b_0
  - s3transfer=0.11.5=pyhd8ed1ab_0
  - safetensors=0.7.0=py313h5c7d99a_0
  - scikit-learn=1.6.1=py313h8ef605b_0
  - scipy=1.15.2=py313h86fcf2b_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sentencepiece=0.2.0=h9ebfe73_10
  - sentencepiece-python=0.2.0=py313h90db370_10
  - sentencepiece-spm=0.2.0=h8e10757_10
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_1
  - statsmodels=0.14.5=py313h29aa505_1
  - sympy=1.14.0=pyh2585a3b_105
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tokenizers=0.21.4=py313h69125a3_0
  - tornado=6.5.2=py313h07c4f96_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.49.0=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=hd6090a7_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xxhash=0.8.3=hb47aa4a_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py313h3dea7bd_0
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py313h54dd161_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - pygments==2.19.2
      - rich==13.9.4
