name: argprism
channels:
  - ursky
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blast=2.16.0=h66d330f_4
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - curl=8.12.1=h332b0f4_0
  - entrez-direct=22.4=he881be0_0
  - gettext=0.23.1=h5888daf_0
  - gettext-tools=0.23.1=h5888daf_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libasprintf=0.23.1=h8e693c7_0
  - libasprintf-devel=0.23.1=h8e693c7_0
  - libcurl=8.12.1=h332b0f4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgettextpo=0.23.1=h5888daf_0
  - libgettextpo-devel=0.23.1=h5888daf_0
  - libgomp=14.2.0=h767d61c_2
  - libidn2=2.3.7=hd590300_0
  - liblzma=5.6.4=hb9d3cd8_0
  - libmpdec=4.0.0=h4bc722e_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libsqlite=3.49.1=hee588c1_1
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncbi-vdb=3.2.0=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.201=pl5321h87f3376_1
  - perl-compress-raw-zlib=2.105=pl5321h87f3376_0
  - perl-encode=3.19=pl5321hec16e2b_1
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.201=pl5321h503566f_4
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h9948957_4
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_4
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321hec16e2b_3
  - perl-scalar-list-utils=1.62=pl5321hec16e2b_1
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pip=25.0.1=pyh145f28c_0
  - python=3.13.2=hf636f53_101_cp313
  - python_abi=3.13=5_cp313
  - readline=8.2=h8c095d6_2
  - rpsbproc=0.5.0=hd6d6fdc_2
  - tk=8.6.13=noxft_h4845f30_101
  - wget=1.21.4=hda4d442_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_1
  - pip:
      - bertviz==1.4.0
      - biopython==1.85
      - boto3==1.37.7
      - botocore==1.37.7
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.17.0
      - fonttools==4.57.0
      - fpdf==1.7.2
      - fsspec==2025.2.0
      - h5py==3.13.0
      - huggingface-hub==0.29.2
      - idna==3.10
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.2.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - s3transfer==0.11.4
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - setuptools==75.8.2
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tokenizers==0.21.0
      - torch==2.6.0
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0

